//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use crate::error::ResourceType;
use super::AppEntity;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "clients")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub access_key: String,
    #[sea_orm(column_type = "Text")]
    pub secret_key: String,
    pub is_active: bool,
    pub create_at: DateTime,
}

impl AppEntity for Model {
    const RESOURCE: ResourceType = ResourceType::Clients;
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
